package rrule

// exceptionWalls builds the set of occurrence wall clocks removed from
// the schedule: explicit EXDATEs plus every instance generated by
// EXRULE. capW bounds an open-ended EXRULE (one with neither COUNT nor
// UNTIL) at the expansion window end so generation always terminates;
// an EXRULE occurrence after the window could not remove anything in
// it anyway.
func (s *Schedule) exceptionWalls(capW WallClock, clock scheduleClock) map[WallClock]bool {
	ex := map[WallClock]bool{}
	for _, e := range s.ExDate {
		ex[naiveOf(e)] = true
	}
	if s.ExRule == nil {
		return ex
	}

	until := clock.untilWall(s.ExRule)
	if until == nil && s.ExRule.Count == 0 {
		c := capW
		until = &c
	}

	start := naiveOf(s.DTStart)
	walls := s.ExRule.generateWalls(start, until, false)
	if !clock.floating {
		filtered := walls[:0]
		for _, w := range walls {
			if clock.exists(w) {
				filtered = append(filtered, w)
			}
		}
		walls = filtered
	}
	if s.ExRule.Count > 0 && len(walls) > s.ExRule.Count {
		walls = walls[:s.ExRule.Count]
	}
	for _, w := range walls {
		ex[w] = true
	}
	return ex
}
