package rrule

import (
	"fmt"
	"time"
)

// This file is the expansion orchestrator. It validates the window,
// asks occurrence.go for timezone-free wall clocks, applies COUNT and
// UNTIL, removes EXDATE/EXRULE instances, merges RDATEs, clips to the
// window and lets zone.go pin survivors to instants. It contains no
// BYxxx math and no zone tables beyond the schedule's own location.

// Expand returns the occurrences of s whose wall-clock start lies in
// the closed window [from, to]. The window must be non-zero and
// from <= to.
//
// The window times use the same convention as s.DTStart: UTC times for
// UTC/floating scheduling of the window for zoned schedules; for
// floating schedules the wall-clock fields are what matters. The
// returned slice is ordered by start time.
//
// DST behaviour for zoned schedules:
//
//   - On a spring-forward, a wall time that does not exist causes that
//     occurrence to be skipped (e.g. 02:30 when 02:00 jumps to 03:00).
//   - On a fall-back, an ambiguous wall time resolves to its first
//     (pre-transition) instant; a single rule instance never expands
//     twice.
func Expand(s *Schedule, from, to time.Time) ([]Occurrence, error) {
	if s == nil {
		return nil, fmt.Errorf("rrule: nil schedule")
	}
	if from.IsZero() || to.IsZero() {
		return nil, fmt.Errorf("rrule: expansion requires a finite [from, to] window")
	}
	if from.After(to) {
		return nil, fmt.Errorf("rrule: from is after to")
	}
	if s.Rule == nil {
		return expandOneShot(s, from, to)
	}

	loc := s.DTStart.Location()
	floating := isFloating(loc)

	fromW := naiveOf(from)
	toW := naiveOf(to)

	untilW := ruleUntil(s.Rule, loc)
	ex := s.exceptionWalls(toW)

	walls := s.Rule.generateWalls(naiveOf(s.DTStart), untilW, true)

	var out []Occurrence
	count := 0
	for _, w := range walls {
		occ, ok := occurrenceAt(w, loc, floating, s.AllDay)
		if !ok {
			// Nonexistent local wall time (spring-forward gap).
			continue
		}
		// A wall clock that vanishes in a spring-forward gap never
		// reaches the counter, so the gap does not consume COUNT.
		count++
		if s.Rule.Count > 0 && count > s.Rule.Count {
			break
		}
		if ex[w] {
			continue
		}
		if w.Before(fromW) || toW.Before(w) {
			continue
		}
		out = append(out, occ)
	}

	// RDATEs add individual instances (subject to EXDATE).
	seen := map[WallClock]bool{}
	for _, o := range out {
		seen[o.Wall] = true
	}
	for _, r := range s.RDate {
		w := naiveOf(r)
		if ex[w] || seen[w] || w.Before(fromW) || toW.Before(w) {
			continue
		}
		occ, ok := occurrenceAt(w, loc, floating, s.AllDay)
		if !ok {
			continue
		}
		out = append(out, occ)
		seen[w] = true
	}

	sortOccurrences(out)
	return out, nil
}

func expandOneShot(s *Schedule, from, to time.Time) ([]Occurrence, error) {
	loc := s.DTStart.Location()
	floating := isFloating(loc)
	w := naiveOf(s.DTStart)
	if s.exceptionWalls(naiveOf(to))[w] {
		return nil, nil
	}
	fw, tw := naiveOf(from), naiveOf(to)
	if w.Before(fw) || tw.Before(w) {
		return nil, nil
	}
	occ, ok := occurrenceAt(w, loc, floating, s.AllDay)
	if !ok {
		return nil, nil
	}
	return []Occurrence{occ}, nil
}

// exceptionWalls builds the set of occurrence wall clocks removed from
// the schedule: explicit EXDATEs plus every instance generated by
// ExRule. capW bounds an open-ended ExRule (one with neither COUNT nor
// UNTIL) at the expansion window end so generation always terminates;
// an ExRule occurrence after the window could not remove anything in
// it anyway.
func (s *Schedule) exceptionWalls(capW WallClock) map[WallClock]bool {
	ex := map[WallClock]bool{}
	for _, e := range s.ExDate {
		ex[naiveOf(e)] = true
	}
	if s.ExRule == nil {
		return ex
	}
	loc := s.DTStart.Location()
	until := ruleUntil(s.ExRule, loc)
	if until == nil && s.ExRule.Count == 0 {
		c := capW
		until = &c
	}
	start := naiveOf(s.DTStart)
	walls := s.ExRule.generateWalls(start, until, false)
	if !isFloating(loc) {
		filtered := walls[:0]
		for _, w := range walls {
			if _, ok := materialize(w, loc); ok {
				filtered = append(filtered, w)
			}
		}
		walls = filtered
	}
	if s.ExRule.Count > 0 && len(walls) > s.ExRule.Count {
		walls = walls[:s.ExRule.Count]
	}
	for _, w := range walls {
		ex[w] = true
	}
	return ex
}

func sortOccurrences(o []Occurrence) {
	// small-slice insertion sort; occurrence counts can be large for
	// DAILY rules but windows stay bounded in practice.
	for i := 1; i < len(o); i++ {
		for j := i; j > 0 && o[j].Wall.Before(o[j-1].Wall); j-- {
			o[j], o[j-1] = o[j-1], o[j]
		}
	}
}
