package rrule

import (
	"fmt"
	"testing"
	"time"
)

// TestRefactorEquivalence compares current Expand with occurrence lists
// generated by the pre-refactor implementation from git HEAD for the
// same parsed rules and windows.
func TestRefactorEquivalence(t *testing.T) {
	ny := loadZone(t, "America/New_York")
	lon := loadZone(t, "Europe/London")

	floatingAt := func(y int, m time.Month, d, h, mi int) time.Time {
		return time.Date(y, m, d, h, mi, 0, 0, Floating)
	}
	nyAt := func(y int, m time.Month, d, h, mi int) time.Time {
		return zonedTime(ny, y, m, d, h, mi)
	}
	lonAt := func(y int, m time.Month, d, h, mi int) time.Time {
		return zonedTime(lon, y, m, d, h, mi)
	}

	cases := []struct {
		name     string
		schedule *Schedule
		from     time.Time
		to       time.Time
	}{
		{
			name: "floating month end negative setpos exdate rdate",
			schedule: &Schedule{
				DTStart: floatingAt(2024, time.January, 31, 9, 0),
				Rule:    mustParse(t, "FREQ=MONTHLY;BYMONTHDAY=31;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=-1;COUNT=4"),
				ExDate:  []time.Time{floatingAt(2024, time.May, 31, 9, 0)},
				RDate:   []time.Time{floatingAt(2024, time.June, 3, 9, 0)},
			},
			from: floatingAt(2024, time.January, 1, 0, 0),
			to:   floatingAt(2024, time.July, 1, 0, 0),
		},
		{
			name: "floating negative month day",
			schedule: &Schedule{
				DTStart: floatingAt(2024, time.February, 29, 9, 0),
				Rule:    mustParse(t, "FREQ=MONTHLY;BYMONTHDAY=-1;COUNT=4"),
			},
			from: floatingAt(2024, time.February, 1, 0, 0),
			to:   floatingAt(2024, time.June, 1, 0, 0),
		},
		{
			name: "ny weekly gap does not consume count",
			schedule: &Schedule{
				DTStart: nyAt(2024, time.March, 3, 2, 0),
				Rule:    mustParse(t, "FREQ=WEEKLY;BYDAY=SU;COUNT=2"),
			},
			from: nyAt(2024, time.March, 1, 0, 0),
			to:   nyAt(2024, time.March, 24, 0, 0),
		},
		{
			name: "ny weekly ambiguous fall back",
			schedule: &Schedule{
				DTStart: nyAt(2024, time.October, 27, 1, 30),
				Rule:    mustParse(t, "FREQ=WEEKLY;BYDAY=SU;COUNT=3"),
			},
			from: nyAt(2024, time.October, 27, 0, 0),
			to:   nyAt(2024, time.November, 11, 0, 0),
		},
		{
			name: "utc until against ny schedule",
			schedule: &Schedule{
				DTStart: nyAt(2024, time.March, 1, 9, 0),
				Rule:    mustParse(t, "FREQ=DAILY;UNTIL=20240305T140000Z"),
			},
			from: nyAt(2024, time.March, 1, 0, 0),
			to:   nyAt(2024, time.March, 10, 0, 0),
		},
		{
			name: "ny exrule own count and rdate",
			schedule: &Schedule{
				DTStart: nyAt(2024, time.July, 1, 9, 0),
				Rule:    mustParse(t, "FREQ=WEEKLY;BYDAY=MO;COUNT=4"),
				ExRule:  mustParse(t, "FREQ=WEEKLY;BYDAY=MO;COUNT=2"),
				RDate:   []time.Time{nyAt(2024, time.July, 4, 9, 0)},
			},
			from: nyAt(2024, time.June, 30, 0, 0),
			to:   nyAt(2024, time.July, 30, 0, 0),
		},
		{
			name: "open floating exrule",
			schedule: &Schedule{
				DTStart: floatingAt(2024, time.March, 4, 9, 0),
				Rule:    mustParse(t, "FREQ=WEEKLY;BYDAY=MO;COUNT=4"),
				ExRule:  mustParse(t, "FREQ=WEEKLY;BYDAY=MO"),
			},
			from: floatingAt(2024, time.March, 1, 0, 0),
			to:   floatingAt(2024, time.March, 31, 0, 0),
		},
		{
			name: "london utc until across dst",
			schedule: &Schedule{
				DTStart: lonAt(2024, time.March, 29, 9, 0),
				Rule:    mustParse(t, "FREQ=DAILY;UNTIL=20240402T090000Z"),
			},
			from: lonAt(2024, time.March, 29, 0, 0),
			to:   lonAt(2024, time.April, 5, 0, 0),
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := Expand(tc.schedule, tc.from, tc.to)
			if err != nil {
				t.Fatal(err)
			}
			have := make([]string, len(got))
			for i, o := range got {
				have[i] = formatLegacyOccurrence(o)
			}
			if len(have) != len(legacyExpandGolden[tc.name]) {
				t.Fatalf("occurrence list changed:\nnew:    %v\nlegacy: %v", have, legacyExpandGolden[tc.name])
			}
			for i := range have {
				if have[i] != legacyExpandGolden[tc.name][i] {
					t.Fatalf("occurrence %d changed:\nnew:    %s\nlegacy: %s", i, have[i], legacyExpandGolden[tc.name][i])
				}
			}
		})
	}
}

func formatLegacyOccurrence(o Occurrence) string {
	wall := fmt.Sprintf("%04d-%02d-%02d %02d:%02d:%02d",
		o.Wall.Year, o.Wall.Month, o.Wall.Day, o.Wall.Hour, o.Wall.Minute, o.Wall.Second)
	if o.Floating {
		return "FLOAT " + wall
	}
	return "ZONED " + wall + " => " + o.Instant.UTC().Format("2006-01-02T15:04:05Z07:00")
}

var legacyExpandGolden = map[string][]string{
	"floating month end negative setpos exdate rdate": {
		"FLOAT 2024-01-31 09:00:00",
		"FLOAT 2024-02-29 09:00:00",
		"FLOAT 2024-03-31 09:00:00",
		"FLOAT 2024-04-30 09:00:00",
		"FLOAT 2024-06-03 09:00:00",
	},
	"floating negative month day": {
		"FLOAT 2024-02-29 09:00:00",
		"FLOAT 2024-03-31 09:00:00",
		"FLOAT 2024-04-30 09:00:00",
		"FLOAT 2024-05-31 09:00:00",
	},
	"ny weekly gap does not consume count": {
		"ZONED 2024-03-03 02:00:00 => 2024-03-03T07:00:00Z",
		"ZONED 2024-03-17 02:00:00 => 2024-03-17T06:00:00Z",
	},
	"ny weekly ambiguous fall back": {
		"ZONED 2024-10-27 01:30:00 => 2024-10-27T05:30:00Z",
		"ZONED 2024-11-03 01:30:00 => 2024-11-03T05:30:00Z",
		"ZONED 2024-11-10 01:30:00 => 2024-11-10T06:30:00Z",
	},
	"utc until against ny schedule": {
		"ZONED 2024-03-01 09:00:00 => 2024-03-01T14:00:00Z",
		"ZONED 2024-03-02 09:00:00 => 2024-03-02T14:00:00Z",
		"ZONED 2024-03-03 09:00:00 => 2024-03-03T14:00:00Z",
		"ZONED 2024-03-04 09:00:00 => 2024-03-04T14:00:00Z",
		"ZONED 2024-03-05 09:00:00 => 2024-03-05T14:00:00Z",
	},
	"ny exrule own count and rdate": {
		"ZONED 2024-07-04 09:00:00 => 2024-07-04T13:00:00Z",
		"ZONED 2024-07-15 09:00:00 => 2024-07-15T13:00:00Z",
		"ZONED 2024-07-22 09:00:00 => 2024-07-22T13:00:00Z",
	},
	"open floating exrule": {},
	"london utc until across dst": {
		"ZONED 2024-03-29 09:00:00 => 2024-03-29T09:00:00Z",
		"ZONED 2024-03-30 09:00:00 => 2024-03-30T09:00:00Z",
		"ZONED 2024-03-31 09:00:00 => 2024-03-31T08:00:00Z",
		"ZONED 2024-04-01 09:00:00 => 2024-04-01T08:00:00Z",
		"ZONED 2024-04-02 09:00:00 => 2024-04-02T08:00:00Z",
	},
}
